name: Bug Report
description: File a bug report to help us improve TrackIt
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: ["Epic-R-R"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below to help us reproduce and fix the issue.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: List the steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Enter data '....'
        3. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment
      placeholder: |
        - OS: [e.g. Ubuntu 22.04, macOS 13.0, Windows 11]
        - Python version: [e.g. 3.11.5]
        - TrackIt version: [e.g. 0.1.0]
        - Installation method: [e.g. pip, git clone]
      render: markdown
    validations:
      required: true

  - type: textarea
    id: command-output
    attributes:
      label: Command output or error message
      description: If applicable, paste the complete command output or error message
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here (screenshots, log files, etc.)
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
