name: Feature Request
description: Suggest a new feature or enhancement for Clockman
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: ["Epic-R-R"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: A clear and concise description of the feature you'd like to see
      placeholder: What would you like Clockman to do?
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem or use case
      description: Describe the problem this feature would solve or the use case it would enable
      placeholder: What specific problem does this solve? What workflow would this improve?
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: Describe how you envision this feature working
      placeholder: How should this feature work? What should the CLI interface look like?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Describe any alternative solutions or features you've considered
      placeholder: Have you considered any workarounds or alternative approaches?
    validations:
      required: false

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature type
      description: What type of feature is this?
      options:
        - New CLI command
        - Enhancement to existing command
        - New output format
        - Performance improvement
        - Integration with external service
        - Configuration option
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my workflow
        - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples about the feature request
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
