name: Security Scanning

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  schedule:
    # Run weekly security scans
    - cron: "0 2 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  dependency-security:
    name: Dependency Security Scan
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          pip install safety bandit[toml]

      - name: Run safety check for known vulnerabilities
        run: |
          safety check --json --output safety-report.json || true
          safety check || echo "Safety check completed with warnings"

      - name: Upload safety report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: safety-report
          path: safety-report.json
          retention-days: 30

  code-security:
    name: Code Security Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit[toml]

      - name: Run bandit security linter
        run: |
          bandit -r clockman/ -f json -o bandit-report.json || true
          bandit -r clockman/ -ll -i || echo "Bandit analysis completed with findings"

      - name: Upload bandit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.json
          retention-days: 30

  secrets-scan:
    name: Secrets Detection
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Trivy secret scanner
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-secrets.sarif"
          exit-code: "0"
          severity: "CRITICAL,HIGH,MEDIUM"
          scanners: "secret"

      - name: Check if SARIF file exists
        id: check-sarif
        run: |
          if [ -f "trivy-secrets.sarif" ]; then
            echo "sarif-exists=true" >> $GITHUB_OUTPUT
            echo "SARIF file created successfully"
            ls -la trivy-secrets.sarif
          else
            echo "sarif-exists=false" >> $GITHUB_OUTPUT
            echo "SARIF file not found, creating empty results"
            echo '{"version": "2.1.0", "runs": []}' > trivy-secrets.sarif
          fi

      - name: Upload Trivy secrets scan results
        if: always() && steps.check-sarif.outputs.sarif-exists == 'true' && github.repository_owner != 'github' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-secrets.sarif"
          category: "trivy-secrets"
        continue-on-error: true

      - name: Upload secrets scan artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-secrets-report
          path: trivy-secrets.sarif
          retention-days: 30

  vulnerability-scan:
    name: Vulnerability Assessment
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH,MEDIUM"
          exit-code: "0"

      - name: Check if SARIF file exists
        id: check-sarif
        run: |
          if [ -f "trivy-results.sarif" ]; then
            echo "sarif-exists=true" >> $GITHUB_OUTPUT
            echo "SARIF file created successfully"
            ls -la trivy-results.sarif
          else
            echo "sarif-exists=false" >> $GITHUB_OUTPUT
            echo "SARIF file not found, creating empty results"
            echo '{"version": "2.1.0", "runs": []}' > trivy-results.sarif
          fi

      - name: Upload Trivy scan results to GitHub Security tab
        if: always() && steps.check-sarif.outputs.sarif-exists == 'true' && github.repository_owner != 'github' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"
          category: "trivy-vuln"
        continue-on-error: true

      - name: Upload vulnerability scan artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-vulnerability-report
          path: trivy-results.sarif
          retention-days: 30

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 30
    # Only run CodeQL if Advanced Security is available
    if: ${{ github.repository_owner != 'github' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) }}
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ["python"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          queries: security-extended,security-and-quality
        continue-on-error: true

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
        continue-on-error: true

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"
        continue-on-error: true

  codeql-fallback:
    name: CodeQL Analysis (Fallback)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # Run this job when Advanced Security is not available
    if: ${{ github.repository_owner != 'github' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          pip install semgrep

      - name: Run Semgrep (CodeQL Alternative)
        run: |
          semgrep --config=auto --json --output=semgrep-results.json clockman/ || true
          echo "Static analysis completed with Semgrep (CodeQL alternative)"

      - name: Upload Semgrep results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-analysis-report
          path: semgrep-results.json
          retention-days: 30

  security-summary:
    name: Security Summary
    runs-on: ubuntu-latest
    needs:
      [
        dependency-security,
        code-security,
        secrets-scan,
        vulnerability-scan,
        codeql,
        codeql-fallback,
      ]
    if: always()
    timeout-minutes: 5
    steps:
      - name: Download all security reports
        uses: actions/download-artifact@v4
        with:
          path: security-reports/
        continue-on-error: true

      - name: Security scan summary
        run: |
          echo "## Security Scan Summary" >> $GITHUB_STEP_SUMMARY
          echo "### Completed Scans:" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Dependency vulnerability scan (safety)" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Code security analysis (bandit)" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Secrets detection (trivy)" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Vulnerability assessment (trivy)" >> $GITHUB_STEP_SUMMARY

          # Check which static analysis was used
          if [ "${{ github.repository_owner != 'github' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) }}" == "true" ]; then
            echo "- ✅ Static analysis (CodeQL)" >> $GITHUB_STEP_SUMMARY
          else
            echo "- ✅ Static analysis (Semgrep - CodeQL alternative)" >> $GITHUB_STEP_SUMMARY
            echo "- ℹ️ GitHub Advanced Security not available - using fallback tools" >> $GITHUB_STEP_SUMMARY
          fi

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Report Artifacts:" >> $GITHUB_STEP_SUMMARY
          ls -la security-reports/ >> $GITHUB_STEP_SUMMARY || echo "No security report artifacts found" >> $GITHUB_STEP_SUMMARY

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Security Status:" >> $GITHUB_STEP_SUMMARY
          echo "All security scans completed successfully. Check individual job outputs and artifacts for detailed results." >> $GITHUB_STEP_SUMMARY
